# Generated by Django 4.0.10 on 2024-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateTimeField()),
                ('job_description', models.TextField(blank=True, null=True)),
                ('uploadedfile', models.FileField(null=True, upload_to='file_upload/')),
            ],
        ),
    ]
