# Generated by Django 4.0.10 on 2024-09-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='job_date',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='uploadedfile',
            field=models.FileField(blank=True, null=True, upload_to='file_upload/'),
        ),
    ]
